package hibernate_4;
// Generated 24-mar-2021 22:28:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private String codDepartamento;
     private String nombreDepartamento;
     private String localidad;
     private Set empleados = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public Departamento(String codDepartamento, String nombreDepartamento, String localidad, Set empleados) {
       this.codDepartamento = codDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.localidad = localidad;
       this.empleados = empleados;
    }
   
    public String getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(String codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


