package hibernate_2;
// Generated 23-mar-2021 23:57:07 by Hibernate Tools 4.3.1



/**
 * Nueva generated by hbm2java
 */
public class Nueva  implements java.io.Serializable {


     private String codDepartamentoN;
     private String nombreDepartamentoN;
     private String localidadN;

    public Nueva() {
    }

	
    public Nueva(String codDepartamentoN) {
        this.codDepartamentoN = codDepartamentoN;
    }
    public Nueva(String codDepartamentoN, String nombreDepartamentoN, String localidadN) {
       this.codDepartamentoN = codDepartamentoN;
       this.nombreDepartamentoN = nombreDepartamentoN;
       this.localidadN = localidadN;
    }
   
    public String getCodDepartamentoN() {
        return this.codDepartamentoN;
    }
    
    public void setCodDepartamentoN(String codDepartamentoN) {
        this.codDepartamentoN = codDepartamentoN;
    }
    public String getNombreDepartamentoN() {
        return this.nombreDepartamentoN;
    }
    
    public void setNombreDepartamentoN(String nombreDepartamentoN) {
        this.nombreDepartamentoN = nombreDepartamentoN;
    }
    public String getLocalidadN() {
        return this.localidadN;
    }
    
    public void setLocalidadN(String localidadN) {
        this.localidadN = localidadN;
    }




}


