package crud.hql;
// Generated 14-mar-2021 23:45:50 by Hibernate Tools 4.3.1



/**
 * DepartamentoNueva generated by hbm2java
 */
public class DepartamentoNueva  implements java.io.Serializable {


     private String codigo;
     private String nombre;

    public DepartamentoNueva() {
    }

    public DepartamentoNueva(String codigo, String nombre) {
       this.codigo = codigo;
       this.nombre = nombre;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


