package crud.hql;
// Generated 14-mar-2021 23:45:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private String codDepartamento;
     private String nombreDepartamento;
     private Set empleados = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String codDepartamento, String nombreDepartamento) {
        this.codDepartamento = codDepartamento;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(String codDepartamento, String nombreDepartamento, Set empleados) {
       this.codDepartamento = codDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.empleados = empleados;
    }
   
    public String getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(String codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


