package crud.hql;
// Generated 14-mar-2021 23:45:50 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String codEmpleado;
     private Departamento departamento;
     private String nombreEmpleado;
     private int salario;

    public Empleado() {
    }

    public Empleado(String codEmpleado, Departamento departamento, String nombreEmpleado, int salario) {
       this.codEmpleado = codEmpleado;
       this.departamento = departamento;
       this.nombreEmpleado = nombreEmpleado;
       this.salario = salario;
    }
   
    public String getCodEmpleado() {
        return this.codEmpleado;
    }
    
    public void setCodEmpleado(String codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }




}


